name: Arduino Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        arduino-platform: ["arduino:avr", "esp8266:esp8266"]
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"
          - arduino-platform: "esp8266:esp8266"
            fqbn: "esp8266:esp8266:nodemcuv2"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      
      - name: Create Arduino CLI config file
        run: |
          mkdir -p ~/.arduino15
          echo 'board_manager:' > ~/.arduino15/arduino-cli.yaml
          echo '  additional_urls: []' >> ~/.arduino15/arduino-cli.yaml

      - name: Add ESP8266 Board Manager URL
        run: |
          arduino-cli config set board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index

      - name: Install platform
        run: arduino-cli core install ${{ matrix.arduino-platform }}

      - name: Install OpenTherm Library from GitHub
        run: |
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli lib install --git-url https://github.com/ihormelnyk/opentherm_library.git

      - name: Install PubSubClient Library
        run: |
          arduino-cli lib install PubSubClient
    
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./OpenTherm2MQTT --warnings more
